### ISSUE TITLE
Feature : Add "Copy Link" button 

### ISSUE THREAD

**Issue by khardikk** [hady68/Link-Saver-Chrome-Ext#3]
I would like to add a "Copy Link" button feature to the Extention. This will allow users to easily copy a specific link to their clipboard with just one click.

![image](https://user-images.githubusercontent.com/64458111/229690280-d63d740f-5aef-400b-8d5b-577fbcc38bc4.png)

Feature Requirements:

A "Copy Link" button should be added to the Link Saver Extension. 
When the button is clicked, the link associated with that specific section or item should be automatically copied to the user's clipboard
The button should have a visual indicator that the link has been copied successfully (e.g. change in color, tooltip, confirmation message)
The feature should work across all modern web browsers

Additional Considerations:

The button should be accessible to users with disabilities (e.g. keyboard-only navigation, screen readers).
The feature should be tested thoroughly before release to ensure it works as intended.

**Comment by NewtonFernandis** [comment]
Hi @hady68 
I will work on this could you please assign it to me?

**Comment by khardikk** [comment]
> Hi @hady68 
> I will work on this could you please assign it to me?

Sure okay, what do you think would be a realistic timeline for you to get this done?

**Comment by NewtonFernandis** [comment]
Its Done Please have a look at the PR and let me know if you need any changes @hady68

**Comment by khardikk** [comment]
> Its Done Please have a look at the PR and let me know if you need any changes @hady68 

 Hey just checked, great work! Have merged the PR!
